apiVersion: v1       # API version ของ Kubernetes สำหรับ Secret
kind: Secret         # ประเภทของ resource คือ Secret
metadata:
  name: app-secret   # ชื่อของ Secret
  namespace: config-demo  # namespace ที่ Secret นี้อยู่
  labels:
    app: config-demo
    type: secret
type: Opaque         # ประเภทของ Secret - Opaque คือประเภททั่วไปไม่มีรูปแบบที่กำหนด
data:                # ข้อมูลใน Secret ต้องเป็น base64-encoded
  db.user: YWRtaW4=      # "admin" ในรูปแบบ base64
  db.password: UGAkJHcwcmQ=  # "P@$$w0rd" ในรูปแบบ base64

# Secret ใช้สำหรับเก็บข้อมูลที่เป็นความลับ เช่น รหัสผ่าน, token, SSH keys
# ข้อมูลจะถูกเก็บในรูปแบบ base64 (ไม่ใช่การเข้ารหัสที่ปลอดภัย แต่เป็นแค่การแปลงรูปแบบ)
# การคำนวณ base64: echo -n "admin" | base64
# การถอดรหัส base64: echo "YWRtaW4=" | base64 --decode
#
# ประเภทของ Secret:
# - Opaque: ใช้เก็บข้อมูลทั่วไป
# - kubernetes.io/tls: สำหรับเก็บ TLS certificates
# - kubernetes.io/dockerconfigjson: สำหรับเก็บ Docker registry authentication
# - kubernetes.io/service-account-token: สำหรับ service account token
#
# Secret ถูกเก็บใน etcd และโดยค่าเริ่มต้นไม่ได้ถูกเข้ารหัส ในระบบที่ต้องการความปลอดภัยสูง
# ควรใช้ etcd encryption หรือโซลูชัน key management ภายนอก เช่น HashiCorp Vault
