apiVersion: v1
kind: ConfigMap
metadata:
  name: web-v1-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Version 1</title>
      <style>
        body { background-color: #f0f8ff; font-family: Arial, sans-serif; text-align: center; padding-top: 50px; }
        h1 { color: #0066cc; }
      </style>
    </head>
    <body>
      <h1>Version 1</h1>
      <p>This is version 1 of the application</p>
      <p>Pod: #1</p>
    </body>
    </html>
  startup.sh: |
    #!/bin/sh
    sed -i "s/POD_NAME_PLACEHOLDER/$HOSTNAME/g" /usr/share/nginx/html/index.html
    exec nginx -g "daemon off;"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-v2-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Version 2</title>
      <style>
        body { background-color: #e6ffe6; font-family: Arial, sans-serif; text-align: center; padding-top: 50px; }
        h1 { color: #009933; }
      </style>
    </head>
    <body>
      <h1>Version 2</h1>
      <p>This is version 2 of the application</p>
      <p>Pod: #2</p>
    </body>
    </html>
  startup.sh: |
    #!/bin/sh
    sed -i "s/POD_NAME_PLACEHOLDER/$HOSTNAME/g" /usr/share/nginx/html/index.html
    exec nginx -g "daemon off;"
