apiVersion: v1
kind: Pod
metadata:
  name: memory-hungry-pod
  namespace: resource-demo
spec:
  containers:
  - name: memory-stress
    image: polinux/stress
    # คำสั่งที่ใช้ในการทดสอบการใช้ทรัพยากร
    command: ["stress"]
    # พารามิเตอร์สำหรับทดสอบการใช้หน่วยความจำ
    # --vm 1: สร้าง worker process 1 ตัว
    # --vm-bytes 150M: ใช้หน่วยความจำ 150 MB
    # --vm-hang 1: ทำให้ process หยุดทำงาน 1 วินาที
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "100Mi" # จองหน่วยความจำขั้นต่ำ 100 Mebibytes
        cpu: "100m"     # จอง CPU ขั้นต่ำ 0.1 cores
      limits:
        memory: "150Mi" # จำกัดหน่วยความจำสูงสุด 150 Mebibytes
        cpu: "200m"     # จำกัด CPU สูงสุด 0.2 cores
