apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: volume-demo
data:
  config.properties: |
    app.name=Example App
    app.version=1.0
    log.level=INFO
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  namespace: volume-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/config/config.properties; sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config  # ตำแหน่งที่จะ mount ConfigMap เป็น volume
  volumes:
  - name: config-volume
    configMap:
      name: example-config  # ชื่อของ ConfigMap ที่สร้างไว้
