apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: volume-demo
  labels:
    app: nginx-demo
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    hostPath:
      path: /tmp/html-data  # hostPath ใช้พื้นที่เก็บข้อมูลจาก Node ที่ Pod ทำงานอยู่
      type: DirectoryOrCreate  # สร้างไดเรกทอรีหากยังไม่มี
