apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi  # กำหนดขนาดพื้นที่เก็บข้อมูลที่จัดสรร
  accessModes:
    - ReadWriteOnce  # โหมดการเข้าถึง: อนุญาตให้เพียง Pod เดียวอ่านและเขียนข้อมูลได้
  persistentVolumeReclaimPolicy: Retain  # นโยบายการเรียกคืน: เก็บข้อมูลไว้หลังจาก PVC ถูกลบ
  hostPath:
    path: /tmp/pv-data  # ตำแหน่งไฟล์ในเครื่อง Host
