apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: volume-demo
type: Opaque
stringData:
  username: admin
  password: mysecretpassword  # ในการใช้งานจริง ไม่ควรเก็บรหัสผ่านในไฟล์ YAML
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: volume-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/secrets/username /etc/secrets/password; sleep 3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets  # ตำแหน่งที่จะ mount Secret เป็น volume
      readOnly: true  # กำหนดให้อ่านได้อย่างเดียว
  volumes:
  - name: secret-volume
    secret:
      secretName: example-secret  # ชื่อของ Secret ที่สร้างไว้
