apiVersion: v1
kind: Service
metadata:
  name: sample-app
  annotations:
    # ไฟล์ Service พื้นฐานสำหรับแอพพลิเคชันตัวอย่าง
    # กำหนดวิธีการเข้าถึงแอพพลิเคชันภายในคลัสเตอร์
    description: "Base service for sample application"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: sample-app
