apiVersion: v1
kind: Service
metadata:
  name: mongodb-admin-ui
  namespace: statefulset-demo
  labels:
    app: mongodb-admin-ui
spec:
  selector:
    app: mongodb-admin-ui
  ports:
  - port: 80
    targetPort: 8081
    name: http
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-admin-ui
  namespace: statefulset-demo
  labels:
    app: mongodb-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-admin-ui
  template:
    metadata:
      labels:
        app: mongodb-admin-ui
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-0.mongodb-headless"
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "password"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "pass"
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"

# Mongo-Express เป็น Web UI สำหรับการจัดการ MongoDB 
# ใช้เพื่อเป็นตัวอย่างของการเข้าถึงแต่ละ Pod ที่อยู่ใน StatefulSet โดยตรง
# โดยใช้การเชื่อมต่อแบบคงที่ผ่าน DNS name ของ headless service
