apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  annotations:
    # ไฟล์สำหรับการแก้ไข (patch) Deployment ในสภาพแวดล้อม dev
    # ใช้สำหรับปรับแต่งค่าเฉพาะสำหรับ development environment
    description: "Development environment specific configuration"
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: sample-app
        # ปรับเปลี่ยน image สำหรับ dev environment
        image: nginx:1.20
        env:
        - name: ENVIRONMENT
          value: "development"
