apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# ไฟล์ Kustomization สำหรับสภาพแวดล้อม development
# ใช้สำหรับปรับแต่งค่าต่างๆ ที่เฉพาะเจาะจงสำหรับ dev environment
resources:
- ../../base
namePrefix: dev-
namespace: development
patchesStrategicMerge:
- deployment-patch.yaml
