apiVersion: v1
kind: Pod
metadata:
  name: adapter-pattern
  namespace: pod-patterns
spec:
  containers:
  - name: app  # คอนเทนเนอร์หลักที่สร้าง log
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo \"$(date): INFO Application message\" >> /var/log/app.log; echo \"$(date): ERROR Application error\" >> /var/log/app.log; sleep 5; done"]
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  - name: log-adapter  # คอนเทนเนอร์ adapter ที่แปลงรูปแบบ log
    image: busybox
    command: ["/bin/sh", "-c", "while true; do grep ERROR /var/log/app.log | awk '{$1=\"ERROR:\"; print}' > /var/transformed/error.log; sleep 5; done"]
    volumeMounts:
    - name: log-volume  # แชร์ volume สำหรับอ่าน log จากแอพพลิเคชั่นหลัก
      mountPath: /var/log
    - name: transformed-logs  # volume สำหรับเก็บ log ที่แปลงรูปแบบแล้ว
      mountPath: /var/transformed
  volumes:
  - name: log-volume
    emptyDir: {}
  - name: transformed-logs
    emptyDir: {}
