apiVersion: v1
kind: Pod
metadata:
  name: ambassador-pattern
  namespace: pod-patterns
spec:
  containers:
  - name: app  # คอนเทนเนอร์หลักที่เรียกใช้บริการผ่าน localhost
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo \"Sending request to: localhost:9000\"; wget -q -O- http://localhost:9000; sleep 5; done"]
  - name: ambassador  # คอนเทนเนอร์ ambassador ที่ทำหน้าที่เชื่อมต่อกับบริการภายนอก
    image: nginx
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-conf  # volume สำหรับ config nginx
    configMap:
      name: nginx-ambassador-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ambassador-config
  namespace: pod-patterns
data:
  default.conf: |
    server {
      listen 9000;
      location / {
        return 200 'Response from mock external service\n';
      }
    }
