FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir gunicorn==23.0.0 Django==4.2.19

# Copy project files
COPY . .

# Run tests by default when the container starts
CMD ["python", "manage.py", "test"]
