name: ZAP Full Scan Example

on:
  schedule:
    - cron: '0 0 * * 1'  # ทุกวันจันทร์เวลาเที่ยงคืน
  workflow_dispatch:     # อนุญาตให้รันด้วยตนเองได้

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    name: ทดสอบความปลอดภัยด้วย ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://www.example.com'
          fail_action: false
          allow_issue_writing: true
          issue_title: 'รายงานการสแกนด้วย ZAP ประจำสัปดาห์'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: zap-results
          path: |
            report.html
            report.json
            report.md
