apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-content
  namespace: replica-demo
  labels:
    app: nginx
    demo: replicas
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to NGINX on Kubernetes</title>
      <style>
        body {
          width: 35em;
          margin: 0 auto;
          font-family: Tahoma, Verdana, Arial, sans-serif;
        }
      </style>
    </head>
    <body>
      <h1>Welcome to NGINX on Kubernetes!</h1>
      <p>If you see this page, your Kubernetes NGINX deployment with Ingress is working correctly.</p>
      
      <h2>Environment Information:</h2>
      <ul>
        <li>Pod Name: NGINX Demo Pod</li>
        <li>Namespace: replica-demo</li>
        <li>Accessed via Ingress: nginx.k8s.local</li>
      </ul>
      
      <p><em>Thank you for using the DevOps Workshop tutorial.</em></p>
    </body>
    </html>
