name: Django Production Deployment

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check Python version
      run: |
        python3 --version
        which python3
        
    - name: Build and run Django tests in Docker
      run: |
        docker build -t django-test:latest -f Dockerfile.test .
        docker run --rm django-test:latest python manage.py check
        docker run --rm django-test:latest
        
    - name: Build and run code linting in Docker
      run: |
        docker build -t django-lint:latest -f Dockerfile.lint .
        docker run --rm django-lint:latest

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    # No Python setup needed for Docker-based deployment
    
    - name: Build Docker Image
      run: |
        docker build -t django-app-main:latest .
        
    - name: Stop existing container
      run: |
        docker rm -f django-app-main || true
        
    - name: Ensure Docker Network Created
      run: |
        if ! docker network inspect backend > /dev/null 2>&1; then
          docker network create backend
        fi
        
    - name: Start container
      run: |
        docker run -d \
          --name django-app-main \
          --network backend \
          -p 8002:8000 \
          -e DJANGO_VERSION=Production \
          -e DEBUG=False \
          --restart always \
          django-app-main:latest
